@base_url = http://localhost:5000

POST {{base_url}}/auth/login

{
    "phoneNumber": "+234(0)9076147178",
    "name": "saad"
}

###

GET {{base_url}}/

###

POST {{base_url}}/

{
    "name": "john",
    "age": 67
}
