@base_url = http://localhost:5000

GET {{base_url}}/

###

POST {{base_url}}/auth/login
Content-Type: application/json

{ 
    "phoneNumber": "+234(0)8100389197",
    "name": "saad",
    "emailAddress": "saadidris23@gmail.com"
}

###

POST {{base_url}}/auth/verify
Content-Type: application/json

{
    "phoneNumber": "+234(0)8100389197",
    "otp": 992811
}

###
