@base_url = http://localhost:5000
@orderId = 690eac7e9c7c1b780899d173 
@companyId = 690d05db3d65bcadaaa0a187


# Initialize Order
POST {{base_url}}/orders
Content-Type: application/json

{ 
    "sender": {
        "name": "Jane Doe",
        "address": "123 Secondary St, City, Country",
        "phoneNumber": "+1234567890",
        "emailAddress": "jane.doe@example.com"
    },
    "receiver": {
        "name": "John Doe",
        "address": "123 Main St, City, Country",
        "phoneNumber": "+1234567890",
        "emailAddress": "john.doe@example.com"
    },
    "weight": 20,
    "distance": 45,
    "description": "pink bag",
    "price": 2000
}

### 
GET {{base_url}}/orders/{{orderId}}


### # confirm Order 
POST {{base_url}}/orders/{{orderId}}/confirm
Content-Type: application/json

{
    "companyId": "{{companyId}}",
    "paymentMethod": "pay_now"
}



# make Payments
###
# track order 
GET {{base_url}}/orders/{{orderId}}/track

# confirm delivery
# review company 

