@base_url = http://localhost:5000
@orderId = 690d075aeb8b074250779809 

POST {{base_url}}/orders
Content-Type: application/json

{ 
    "sender": {
        "name": "Jane Doe",
        "address": "123 Secondary St, City, Country",
        "phoneNumber": "+1234567890",
        "emailAddress": "jane.doe@example.com"
    },
    "receiver": {
        "name": "John Doe",
        "address": "123 Main St, City, Country",
        "phoneNumber": "+1234567890",
        "emailAddress": "john.doe@example.com"
    },
    "weight": 20,
    "distance": 45,
    "description": "pink bag",
    "price": 2000
}

###
GET {{base_url}}/orders/{{orderId}}